[browser]
gatherUsageStats = false
[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
[client]
showErrorDetails = false
[theme]
base = "dark"
primaryColor = "#5C6CFF"
backgroundColor = "#313339"
secondaryBackgroundColor = "#222328"