[browser]
gatherUsageStats = false
[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
[client]
showErrorDetails = false
[theme]
base = "dark"
primaryColor = "#5462EB"
backgroundColor = "#313339"
secondaryBackgroundColor = "#2e3036"